### ISSUE TITLE
Evaluación - Infografía de las Librerias.

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/infografia-de-las-librerias-salathiel1999#2]
### - **Evaluación con inforgrafía:**

> Puntaje: 20 %.

[Rubrica Infografía - Irvin Barrera.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-salathiel1999/files/6362889/Rubrica.Infografia.-.Irvin.Barrera.pdf)

- Evalúo Yabin España Aparicio.

**Comment by josealfredo79** [comment]
Se debe subir los trabajos en la ISSUES...por favor.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
